GET localhost:8080/api/company/zara.com

#GET peaceful-woodland-36950.herokuapp.com/api/company/eleks.com

###
POST localhost:8080/api/company
Content-Type: application/json

{
  "name": "zara",
  "employees": "5000",
  "domain": "zara.com"
}


###
POST localhost:8080/api/company
Content-Type: application/json

{
  "name": "softerve",
  "employees": "10000",
  "domain": "softserveinc.com"
}


###
POST peaceful-woodland-36950.herokuapp.com/api/company
Content-Type: application/json

{
  "name": "eleks",
  "domain": "eleks.com"
}
